### ISSUE TITLE
ValueError: not enough values to unpack (expected at least 7, got 4)

### ISSUE THREAD

**Issue by Quadwo** [davide-coccomini/TimeSformer-Video-Classification#2]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-36-804a93c17b78> in <module>
     26 learning_rate = 1e-4
     27 for t in range(ITERATIONS):
---> 28   y_pred = model(torch.FloatTensor(np.asarray(video)))
     29 
     30   loss = loss_fn(y_pred, torch.tensor(labels))

~\anaconda3\lib\site-packages\torch\nn\modules\module.py in _call_impl(self, *input, **kwargs)
    725             result = self._slow_forward(*input, **kwargs)
    726         else:
--> 727             result = self.forward(*input, **kwargs)
    728         for hook in itertools.chain(
    729                 _global_forward_hooks.values(),

~\anaconda3\lib\site-packages\torch\nn\modules\container.py in forward(self, input)
    115     def forward(self, input):
    116         for module in self:
--> 117             input = module(input)
    118         return input
    119 

~\anaconda3\lib\site-packages\torch\nn\modules\module.py in _call_impl(self, *input, **kwargs)
    725             result = self._slow_forward(*input, **kwargs)
    726         else:
--> 727             result = self.forward(*input, **kwargs)
    728         for hook in itertools.chain(
    729                 _global_forward_hooks.values(),

<ipython-input-15-9713d1cb4f0b> in forward(self, video)
     42 
     43     def forward(self, video):
---> 44         b, f, _, h, w, *_, device, p = *video.shape, video.device, self.patch_size
     45         assert h % p == 0 and w % p == 0, f'height {h} and width {w} of video must be divisible by the patch size {p}'
     46 

ValueError: not enough values to unpack (expected at least 7, got 4)

**Comment by davide-coccomini** [comment]
Hi, are you sure you are correctly reading your dataset?

**Comment by Quadwo** [comment]
> Hi, are you sure you are correctly reading your dataset?

Yes. Apparently, I'm running this code locally but on Colab it works perfectly. So I don't know why I get this error.

**Comment by davide-coccomini** [comment]
It is probably an error in the path you are using. Be sure that the BASE_DIR is correctly initialized too.

**Comment by Quadwo** [comment]
> It is probably an error in the path you are using. Be sure that the BASE_DIR is correctly initialized too.

Alright thank you very much

**Comment by davide-coccomini** [comment]
> > It is probably an error in the path you are using. Be sure that the BASE_DIR is correctly initialized too.
> 
> Alright thank you very much

No problem, let me know if you need help to solve it.
